name: Ruff

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Ruff
      uses: astral-sh/ruff-action@v3.2.2
    - name: Ruff Actions
      run: |
        ruff check --fix
        ruff format
    - name: Add and Commit
      uses: EndBug/add-and-commit@v9
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        default_author: github_actions
        pathspec_error_handling: ignore
